### ISSUE TITLE
Drop Pod Support Power causes MP desync 

### ISSUE THREAD

**Issue by Inq8** [Inq8/CAmod#3]
Overhaul Drop pod support power required.

1. Causes MP Desync

2. First actor created spawns flying the wrong direction (mirrored)

**Comment by GraionDilach** [comment]
1) is caused by the CosmeticRandom here and needs to be World.SharedRandom:

https://github.com/Inq8/CAmod/blob/5f9bd7777761120640d00a05d147cd38b628379e/OpenRA.Mods.CA/Traits/SupportPowers/DropPodsPower.cs#L105

**Comment by Inq8** [comment]
Thanks to @GraionDilach, fixed 1, 2 remains but the ability will be remade in the future. closing.

**Comment by Inq8** [comment]
Appears desync still occurs:

```OpenRA engine version d006601
Combined Arms mod version 0.61-Pre-Release-5
on map 23807f72a00d796acd5275fb9d4b7f4783ed5ff6 (Reaver's Divide by Darkademic).
Date: 2020-01-23 15:08:54Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Out of sync in frame 4277.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame)
   at OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   at OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```
my friend sent me it, and has sent me the replay so i can have a look when i get home

**Comment by GraionDilach** [comment]
https://github.com/Inq8/CAmod/blob/5f9bd7777761120640d00a05d147cd38b628379e/OpenRA.Mods.CA/Warheads/SpawnRandomActorWarhead.cs#L95

This is also a source of reconnection error. I don't know if this one is involved in your drop pods though.

**Comment by Inq8** [comment]
Ahh that will be it. thanks
