### ISSUE TITLE
Crash on master

### ISSUE THREAD

**Issue by dnqbob** [Inq8/CAmod#59]
on ee778c8f9f95597c17f4a82b8aced0d84795bf52

[ca-2024-02-16T082841Z.zip](https://github.com/Inq8/CAmod/files/14309089/ca-2024-02-16T082841Z.zip)

```
[2024-02-16T16:28:39] Game started
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   at OpenRA.Traits.Target.get_CenterPosition() in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Traits\Target.cs:line 169
   at OpenRA.Mods.CA.Activities.CruiseMissileFly..ctor(Actor self, Target t, CruiseMissile cm, WDist maxAltitude, WDist maxTargetMovement, Boolean trackTarget) in D:\work\Projects\Github\camod-mirror\OpenRA.Mods.CA\Activities\CruiseMissileFly.cs:line 59
   at OpenRA.Mods.CA.Traits.CruiseMissile.GetActivity(Actor self, Target target) in D:\work\Projects\Github\camod-mirror\OpenRA.Mods.CA\Traits\CruiseMissile.cs:line 91
   at OpenRA.Mods.CA.Traits.MissileBase.OpenRA.Traits.INotifyAddedToWorld.AddedToWorld(Actor self) in D:\work\Projects\Github\camod-mirror\OpenRA.Mods.CA\Traits\MissileBase.cs:line 129
   at OpenRA.World.Add(Actor a) in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\World.cs:line 341
   at OpenRA.Mods.CA.Traits.MissileSpawnerMaster.<>c__DisplayClass17_0.<SpawnIntoWorld>b__0(World w) in D:\work\Projects\Github\camod-mirror\OpenRA.Mods.CA\Traits\MissileSpawnerMaster.cs:line 207
   at OpenRA.World.Tick() in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\World.cs:line 453
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Game.cs:line 630
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Game.cs:line 645
   at OpenRA.Game.Loop() in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Game.cs:line 814
   at OpenRA.Game.Run() in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Game.cs:line 867
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Game\Game.cs:line 305
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\camod-mirror\engine\OpenRA.Launcher\Program.cs:line 32

terminate called without an active exception
```

Guess you need a target check at CruiseMissileFly.cs:line 59.

**Comment by dnqbob** [comment]
@Inq8 I think this issue was solved months ago?

**Comment by dnqbob** [comment]
I think it should be fixed now
