### ISSUE TITLE
crash at online game version 1.03

### ISSUE THREAD

**Issue by madz12345** [Inq8/CAmod#63]
Today i have crash online game. Replay in attachment.
[
[info.zip](https://github.com/user-attachments/files/16651993/info.zip)
](url)
Best regards

OpenRA engine version ca-engine/1.02
OpenRA Language: en
Combined Arms mod version 1.03
on map 9fc1f192ac4c70aa2f35b8b0457e7fc0c9d4a95e (Obsidian 5v5 by Darkademic).
Date: 2024-08-18 15:26:37Z
Operating System: Windows (X64, Microsoft Windows NT 10.0.22631.0)
Runtime Version: .NET CLR 6.0.32
Installed Language: pl (Installed) pl (Current) pl (Current UI)
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (cvat 36725 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.CloneProducer.UnitProduced(Actor unit) in /home/runner/work/CAmod/CAmod/OpenRA.Mods.CA/Traits/CloneProducer.cs:line 90
   at OpenRA.Mods.Common.Traits.CloneSource.OpenRA.Mods.Common.Traits.INotifyProduction.UnitProduced(Actor self, Actor other, CPos exit) in /home/runner/work/CAmod/CAmod/OpenRA.Mods.CA/Traits/CloneSource.cs:line 69
   at OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass6_0.<DoProduction>b__0(World w) in /home/runner/work/CAmod/CAmod/engine/OpenRA.Mods.Common/Traits/Production.cs:line 99
   at OpenRA.World.Tick() in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/World.cs:line 453
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/Game.cs:line 630
   at OpenRA.Game.LogicTick() in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/Game.cs:line 645
   at OpenRA.Game.Loop() in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/Game.cs:line 814
   at OpenRA.Game.Run() in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/Game.cs:line 867
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/CAmod/CAmod/engine/OpenRA.Game/Game.cs:line 305
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args) in /home/runner/work/CAmod/CAmod/engine/OpenRA.WindowsLauncher/Program.cs:line 71

**Comment by darkademic** [comment]
Fixed in 1.04.
